INSERT INTO customer_orders (customer_name, amount, status, created_at) VALUES
('Alice',   120.50, 'completed', NOW() - INTERVAL '5 days'),
('Bob',      89.99, 'pending',   NOW() - INTERVAL '4 days'),
('Charlie', 250.00, 'completed', NOW() - INTERVAL '3 days'),
('David',    45.00, 'cancelled', NOW() - INTERVAL '2 days'),
('Emma',    500.00, 'completed', NOW() - INTERVAL '1 day'),
('Frank',    30.00, 'pending',   NOW()),
('Grace',   175.25, 'completed', NOW()),
('Helen',    60.00, 'completed', NOW()),
('Ivan',      0.00, 'cancelled', NOW()),
('Julia',   310.00, 'completed', NOW()),
('Kevin',    22.00, 'pending',   NOW()),
('Laura',   145.75, 'completed', NOW()),
('Mike',     78.20, 'completed', NOW()),
('Nina',    410.10, 'cancelled', NOW()),
('Oscar',   260.00, 'completed', NOW()),
('Paul',     55.50, 'pending',   NOW()),
('Queen',   700.00, 'completed', NOW()),
('Ryan',    135.40, 'completed', NOW()),
('Sarah',    92.30, 'pending',   NOW()),
('Tom',     180.00, 'completed', NOW());